import { InMemoryDbService } from 'angular-in-memory-web-api';
export class DocumentInMemoryData implements InMemoryDbService {
  createDb() {
    let document = [{
  "id": 1,
  "filename": "Ipsum.ppt",
  "filepath": "com.wikia.Quo Lux"
}, {
  "id": 2,
  "filename": "PlateaDictumstMorbi.xls",
  "filepath": "com.wunderground.Rank"
}, {
  "id": 3,
  "filename": "SitAmetNunc.ppt",
  "filepath": "ru.yandex.Rank"
}, {
  "id": 4,
  "filename": "SedMagnaAt.ppt",
  "filepath": "edu.washington.Zamit"
}, {
  "id": 5,
  "filename": "DolorSitAmet.ppt",
  "filepath": "gov.house.Overhold"
}, {
  "id": 6,
  "filename": "Quisque.pdf",
  "filepath": "jp.ne.hatena.Alphazap"
}, {
  "id": 7,
  "filename": "Diam.doc",
  "filepath": "com.quantcast.Trippledex"
}, {
  "id": 8,
  "filename": "LoremInteger.ppt",
  "filepath": "com.amazonaws.Viva"
}, {
  "id": 9,
  "filename": "JustoPellentesqueViverra.xls",
  "filepath": "com.live.Bamity"
}, {
  "id": 10,
  "filename": "ConsequatMetusSapien.ppt",
  "filepath": "com.hugedomains.Aerified"
}, {
  "id": 11,
  "filename": "GravidaSem.pdf",
  "filepath": "com.bravesites.Y-Solowarm"
}, {
  "id": 12,
  "filename": "UltricesLiberoNon.ppt",
  "filepath": "com.jigsy.Mat Lam Tam"
}, {
  "id": 13,
  "filename": "LectusAliquamSit.ppt",
  "filepath": "com.marriott.Home Ing"
}, {
  "id": 14,
  "filename": "Duis.xls",
  "filepath": "mil.army.Bigtax"
}, {
  "id": 15,
  "filename": "MaurisViverraDiam.doc",
  "filepath": "jp.ameblo.Home Ing"
}, {
  "id": 16,
  "filename": "Id.ppt",
  "filepath": "com.nymag.Otcom"
}, {
  "id": 17,
  "filename": "CrasMiPede.xls",
  "filepath": "com.sciencedirect.Zoolab"
}, {
  "id": 18,
  "filename": "IdNisl.xls",
  "filepath": "com.bloglines.Flexidy"
}, {
  "id": 19,
  "filename": "Orci.xls",
  "filepath": "uk.co.guardian.Tresom"
}, {
  "id": 20,
  "filename": "IaculisJustoIn.xls",
  "filepath": "com.google.Ventosanzap"
}, {
  "id": 21,
  "filename": "Curabitur.doc",
  "filepath": "com.sogou.Matsoft"
}, {
  "id": 22,
  "filename": "Nulla.pdf",
  "filepath": "jp.co.rakuten.Rank"
}, {
  "id": 23,
  "filename": "Dictumst.xls",
  "filepath": "ru.odnoklassniki.Vagram"
}, {
  "id": 24,
  "filename": "PedeLiberoQuis.doc",
  "filepath": "com.weibo.Treeflex"
}, {
  "id": 25,
  "filename": "UltricesAliquetMaecenas.ppt",
  "filepath": "com.go.Asoka"
}, {
  "id": 26,
  "filename": "Pellentesque.xls",
  "filepath": "org.npr.Lotlux"
}, {
  "id": 27,
  "filename": "UtTellusNulla.ppt",
  "filepath": "jp.ne.so-net.Sonair"
}, {
  "id": 28,
  "filename": "EtiamPretiumIaculis.xls",
  "filepath": "de.1und1.Sonair"
}, {
  "id": 29,
  "filename": "Nunc.ppt",
  "filepath": "com.yellowpages.Zoolab"
}, {
  "id": 30,
  "filename": "CubiliaCurae.xls",
  "filepath": "com.quantcast.Stringtough"
}, {
  "id": 31,
  "filename": "MassaIdLobortis.doc",
  "filepath": "gov.nih.Zoolab"
}, {
  "id": 32,
  "filename": "CurabiturConvallis.xls",
  "filepath": "jp.japanpost.Flexidy"
}, {
  "id": 33,
  "filename": "Enim.ppt",
  "filepath": "jp.ne.goo.Lotstring"
}, {
  "id": 34,
  "filename": "Eget.ppt",
  "filepath": "edu.umn.Flexidy"
}, {
  "id": 35,
  "filename": "Proin.xls",
  "filepath": "uk.co.bbc.Konklux"
}, {
  "id": 36,
  "filename": "Dictumst.doc",
  "filepath": "uk.co.ebay.Gembucket"
}, {
  "id": 37,
  "filename": "VestibulumSedMagna.ppt",
  "filepath": "com.businessinsider.Lotstring"
}, {
  "id": 38,
  "filename": "PlateaDictumstEtiam.ppt",
  "filepath": "com.mayoclinic.Konklab"
}, {
  "id": 39,
  "filename": "Vestibulum.ppt",
  "filepath": "gov.senate.Wrapsafe"
}, {
  "id": 40,
  "filename": "SitAmet.xls",
  "filepath": "com.salon.Tin"
}, {
  "id": 41,
  "filename": "VivamusTortor.xls",
  "filepath": "com.acquirethisname.Fixflex"
}, {
  "id": 42,
  "filename": "ViverraDiamVitae.xls",
  "filepath": "com.chicagotribune.Pannier"
}, {
  "id": 43,
  "filename": "OdioIn.ppt",
  "filepath": "hk.com.google.Latlux"
}, {
  "id": 44,
  "filename": "IdLigula.pdf",
  "filepath": "com.reuters.Cardify"
}, {
  "id": 45,
  "filename": "OdioCurabiturConvallis.ppt",
  "filepath": "com.stumbleupon.Matsoft"
}, {
  "id": 46,
  "filename": "Odio.ppt",
  "filepath": "gov.house.Aerified"
}, {
  "id": 47,
  "filename": "Rhoncus.xls",
  "filepath": "com.shareasale.Home Ing"
}, {
  "id": 48,
  "filename": "Vel.xls",
  "filepath": "com.cisco.Konklux"
}, {
  "id": 49,
  "filename": "SitAmetNunc.xls",
  "filepath": "hk.com.google.Bigtax"
}, {
  "id": 50,
  "filename": "ViverraPede.ppt",
  "filepath": "uk.co.timesonline.Pannier"
}, {
  "id": 51,
  "filename": "Tristique.xls",
  "filepath": "com.xinhuanet.Konklab"
}, {
  "id": 52,
  "filename": "AugueLuctusTincidunt.ppt",
  "filepath": "com.1688.Redhold"
}, {
  "id": 53,
  "filename": "PraesentLectus.ppt",
  "filepath": "edu.psu.Fix San"
}, {
  "id": 54,
  "filename": "DuisBibendumMorbi.doc",
  "filepath": "edu.arizona.Andalax"
}, {
  "id": 55,
  "filename": "Sapien.xls",
  "filepath": "ru.rambler.Regrant"
}, {
  "id": 56,
  "filename": "PurusPhasellusIn.ppt",
  "filepath": "com.studiopress.Flowdesk"
}, {
  "id": 57,
  "filename": "FaucibusOrciLuctus.ppt",
  "filepath": "com.tripod.Sonsing"
}, {
  "id": 58,
  "filename": "ViverraPedeAc.ppt",
  "filepath": "org.archive.Mat Lam Tam"
}, {
  "id": 59,
  "filename": "CubiliaCurae.ppt",
  "filepath": "gov.usda.Home Ing"
}, {
  "id": 60,
  "filename": "NisiVulputateNonummy.pdf",
  "filepath": "com.arstechnica.Span"
}, {
  "id": 61,
  "filename": "SapienIaculisCongue.ppt",
  "filepath": "net.seesaa.Redhold"
}, {
  "id": 62,
  "filename": "Magna.xls",
  "filepath": "org.gmpg.Bitchip"
}, {
  "id": 63,
  "filename": "Cras.xls",
  "filepath": "com.wix.Zaam-Dox"
}, {
  "id": 64,
  "filename": "TempusSitAmet.ppt",
  "filepath": "com.usnews.Sub-Ex"
}, {
  "id": 65,
  "filename": "Odio.ppt",
  "filepath": "gov.fda.Tres-Zap"
}, {
  "id": 66,
  "filename": "NibhFusceLacus.ppt",
  "filepath": "ru.vkontakte.Tres-Zap"
}, {
  "id": 67,
  "filename": "UllamcorperPurus.xls",
  "filepath": "it.google.Temp"
}, {
  "id": 68,
  "filename": "Diam.xls",
  "filepath": "net.seesaa.Tresom"
}, {
  "id": 69,
  "filename": "Ut.ppt",
  "filepath": "org.apache.Bamity"
}, {
  "id": 70,
  "filename": "Amet.xls",
  "filepath": "com.alibaba.Sonair"
}, {
  "id": 71,
  "filename": "AugueLuctusTincidunt.xls",
  "filepath": "net.comcast.Regrant"
}, {
  "id": 72,
  "filename": "VivamusTortor.xls",
  "filepath": "com.youtube.Span"
}, {
  "id": 73,
  "filename": "ElementumEu.ppt",
  "filepath": "com.issuu.Lotlux"
}, {
  "id": 74,
  "filename": "Orci.doc",
  "filepath": "com.tripod.Keylex"
}, {
  "id": 75,
  "filename": "CurabiturConvallisDuis.xls",
  "filepath": "com.deliciousdays.Span"
}, {
  "id": 76,
  "filename": "Congue.pdf",
  "filepath": "com.yellowbook.Lotlux"
}, {
  "id": 77,
  "filename": "AtNuncCommodo.xls",
  "filepath": "com.hubpages.Bytecard"
}, {
  "id": 78,
  "filename": "QuisOrci.ppt",
  "filepath": "com.1688.Stringtough"
}, {
  "id": 79,
  "filename": "PellentesqueUltrices.doc",
  "filepath": "com.scientificamerican.Vagram"
}, {
  "id": 80,
  "filename": "Faucibus.ppt",
  "filepath": "com.nationalgeographic.Solarbreeze"
}, {
  "id": 81,
  "filename": "Eu.ppt",
  "filepath": "com.barnesandnoble.Andalax"
}, {
  "id": 82,
  "filename": "CuraeDonec.ppt",
  "filepath": "fr.unblog.Zaam-Dox"
}, {
  "id": 83,
  "filename": "Varius.xls",
  "filepath": "com.over-blog.Ventosanzap"
}, {
  "id": 84,
  "filename": "SapienSapienNon.ppt",
  "filepath": "org.apache.Veribet"
}, {
  "id": 85,
  "filename": "DignissimVestibulum.ppt",
  "filepath": "com.cnbc.Kanlam"
}, {
  "id": 86,
  "filename": "LeoOdio.ppt",
  "filepath": "com.elpais.Sonsing"
}, {
  "id": 87,
  "filename": "Consectetuer.xls",
  "filepath": "com.marketwatch.Veribet"
}, {
  "id": 88,
  "filename": "Leo.xls",
  "filepath": "com.imdb.Redhold"
}, {
  "id": 89,
  "filename": "FelisUtAt.xls",
  "filepath": "com.sogou.Zaam-Dox"
}, {
  "id": 90,
  "filename": "InHac.pdf",
  "filepath": "jp.ne.goo.Otcom"
}, {
  "id": 91,
  "filename": "Est.xls",
  "filepath": "com.reference.Home Ing"
}, {
  "id": 92,
  "filename": "IdMassa.ppt",
  "filepath": "gov.va.Trippledex"
}, {
  "id": 93,
  "filename": "Nisl.xls",
  "filepath": "org.wikimedia.Toughjoyfax"
}, {
  "id": 94,
  "filename": "AugueQuam.pdf",
  "filepath": "com.geocities.Asoka"
}, {
  "id": 95,
  "filename": "NonVelit.xls",
  "filepath": "com.cisco.Ronstring"
}, {
  "id": 96,
  "filename": "InFaucibus.xls",
  "filepath": "org.gmpg.Matsoft"
}, {
  "id": 97,
  "filename": "NecNisiVolutpat.xls",
  "filepath": "com.mapquest.Domainer"
}, {
  "id": 98,
  "filename": "AIpsum.ppt",
  "filepath": "com.technorati.Y-Solowarm"
}, {
  "id": 99,
  "filename": "EtUltrices.xls",
  "filepath": "ru.ucoz.Toughjoyfax"
}, {
  "id": 100,
  "filename": "Aliquam.xls",
  "filepath": "cc.tiny.Voltsillam"
}];
    return {document};
  }
}
